/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddCategory: typeof import('./src/components/AddCategory.vue')['default']
    AddNewCategory: typeof import('./src/components/renderSetting/AddNewCategory.vue')['default']
    BackgroundSetting: typeof import('./src/components/panel/BackgroundSetting.vue')['default']
    CameraSetting: typeof import('./src/components/panel/CameraSetting.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    HdrLibrary: typeof import('./src/components/library/HdrLibrary.vue')['default']
    LibraryItem: typeof import('./src/components/library/LibraryItem.vue')['default']
    LightSetting: typeof import('./src/components/panel/LightSetting.vue')['default']
    MaterialLibrary: typeof import('./src/components/library/MaterialLibrary.vue')['default']
    MaterialsSetting: typeof import('./src/components/panel/MaterialsSetting.vue')['default']
    ModelSetting: typeof import('./src/components/modelSetting/ModelSetting.vue')['default']
    PanelMain: typeof import('./src/components/panel/PanelMain.vue')['default']
    RenderMain: typeof import('./src/components/renderSetting/RenderMain.vue')['default']
    RenderSetting: typeof import('./src/components/renderSetting/RenderSetting.vue')['default']
    SceneHeader: typeof import('./src/components/sceneHeader/SceneHeader.vue')['default']
    SceneLibrary: typeof import('./src/components/library/SceneLibrary.vue')['default']
    SceneModel: typeof import('./src/components/sceneModel/SceneModel.vue')['default']
    SceneRender: typeof import('./src/components/sceneRender/SceneRender.vue')['default']
    SceneToggle: typeof import('./src/components/renderSetting/SceneToggle.vue')['default']
    SelectNav: typeof import('./src/components/selectNav/SelectNav.vue')['default']
    SettingItem: typeof import('./src/components/SettingItem.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    UploadSetting: typeof import('./src/components/UploadSetting.vue')['default']
    VcDrawer: typeof import('./src/components/VcDrawer.vue')['default']
  }
}
